# Generated by Django 4.0.4 on 2025-07-29 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import holc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0053_alter_users_verificationscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolcMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delegate', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_delegate', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='HolcModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(default=holc.models.generate_unique_code, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation_key', models.PositiveBigIntegerField(default=holc.models.generate_unique_invitation_key, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vote.districts')),
            ],
        ),
        migrations.CreateModel(
            name='VoteOutHolcMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_outs', to='holc.holcmembers')),
                ('holc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='holc.holcmodel')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteInHolcMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_ins', to='holc.holcmembers')),
                ('holc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='holc.holcmodel')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PutFarwardHolcMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='put_farward', to='holc.holcmembers')),
                ('holc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='holc.holcmodel')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='holcmembers',
            name='holc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holc.holcmodel'),
        ),
        migrations.AddField(
            model_name='holcmembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
