# Generated by Django 4.0.4 on 2025-07-29 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PutForwardHolcMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='put_forward', to='holc.holcmembers')),
                ('holc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='holc.holcmodel')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PutFarwardHolcMember',
        ),
    ]
