# Generated by Django 4.0.4 on 2025-08-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holc', '0002_putforwardholcmember_delete_putfarwardholcmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='holcmodel',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
