# Generated by Django 4.0.4 on 2025-08-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holc', '0003_holcmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolcMemberContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_rules', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holc.holcmodel')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holc_contact', to='holc.holcmembers')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
