# Generated by Django 4.0.4 on 2025-08-11 13:53

from django.db import migrations


def populate_holc_member_contact_info(apps, schema_editor):
    HolcMembers = apps.get_model('holc', 'HolcMembers')
    HolcMemberContact = apps.get_model('holc', 'HolcMemberContact')
    
    # Get all Holc members and create contact info for them
    holc_members = HolcMembers.objects.all()
    contact_records = []
    
    for member in holc_members:
        contact_records.append(
            HolcMemberContact(
                member=member,
                holc=member.holc,  # Add the holc reference
                legal_name='',
                contact_rules='',
                address='',
                contact='',
                phone='',
                email=''
            )
        )
    
    # Bulk create all contact info records
    HolcMemberContact.objects.bulk_create(contact_records, ignore_conflicts=True)


def reverse_populate_holc_member_contact_info(apps, schema_editor):
    HolcMemberContact = apps.get_model('holc', 'HolcMemberContact')
    HolcMemberContact.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('holc', '0005_holcmembercontact'),
    ]

    operations = [
        migrations.RunPython(
            populate_holc_member_contact_info,
            reverse_populate_holc_member_contact_info
        ),
    ]
