# Generated by Django 4.0.4 on 2025-08-16 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holc', '0006_populate_holc_member_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolcBackNForthChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('holc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='holc.holcmodel')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='holc.holcbacknforthchat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='holcbacknforthchat',
            index=models.Index(fields=['holc', '-timestamp'], name='holc_holcba_holc_id_c5bcfc_idx'),
        ),
        migrations.AddIndex(
            model_name='holcbacknforthchat',
            index=models.Index(fields=['sender'], name='holc_holcba_sender__9d8e99_idx'),
        ),
        migrations.AddIndex(
            model_name='holcbacknforthchat',
            index=models.Index(fields=['is_deleted'], name='holc_holcba_is_dele_acf41a_idx'),
        ),
    ]
