# Generated by Django 4.0.4 on 2025-10-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holc', '0007_holcbacknforthchat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteoutholcmember',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='voteoutholcmember',
            name='holc',
        ),
        migrations.RemoveField(
            model_name='voteoutholcmember',
            name='voter',
        ),
        migrations.AlterField(
            model_name='holcmodel',
            name='invitation_key',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='VoteInHolcMember',
        ),
        migrations.DeleteModel(
            name='VoteOutHolcMember',
        ),
    ]
