# Generated by Django 4.0.4 on 2025-10-06 21:33

import django.core.validators
from django.db import migrations, models
import holc.models


class Migration(migrations.Migration):

    dependencies = [
        ('holc', '0008_remove_voteoutholcmember_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holcmodel',
            name='code',
            field=models.PositiveIntegerField(default=holc.models.generate_unique_code, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
