# Generated by Django 4.0.4 on 2026-09-20 14:48

import django.core.validators
from django.db import migrations, models
import holc.models


class Migration(migrations.Migration):

    dependencies = [
        ('holc', '0009_alter_holcmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holcmodel',
            name='code',
            field=models.PositiveIntegerField(default=holc.models.generate_unique_code, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddConstraint(
            model_name='holcmodel',
            constraint=models.UniqueConstraint(fields=('district', 'code'), name='unique_caucus_code_per_district'),
        ),
    ]
