# Generated by Django 4.0.4 on 2026-09-20 15:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0061_accountkey_circlekey_circlekeyenvelope_and_more'),
        ('holc', '0010_caucus_code_per_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holcmodel',
            name='code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.CreateModel(
            name='CaucusNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_issued', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caucus_number_sequence', to='vote.districts')),
            ],
        ),
    ]
