# Generated by Django 4.0.4 on 2026-09-22 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holc', '0012_seed_caucus_number_sequences'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaucusAdmissionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_votes', to='holc.holcmembers')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caucus_admission_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['voted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='caucusadmissionvote',
            constraint=models.UniqueConstraint(fields=('voter', 'application'), name='unique_caucus_admission_vote'),
        ),
    ]
