# Generated by Django 4.0.4 on 2026-09-22 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holc', '0013_caucusadmissionvote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaucusExpulsionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_membership_id', models.PositiveBigIntegerField()),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('caucus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expulsion_votes', to='holc.holcmodel')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caucus_expulsion_votes_received', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caucus_expulsion_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['voted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='caucusexpulsionvote',
            constraint=models.UniqueConstraint(fields=('voter', 'caucus', 'target_membership_id'), name='unique_caucus_expulsion_vote'),
        ),
    ]
