# Generated by Django 4.0.4 on 2026-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holc', '0015_putforwardholcmember_unique_holc_replacement_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='holcmembers',
            name='succession_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
