version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-dsup
    restart: always
    environment:
      POSTGRES_DB: db_dsup
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: pass_admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    container_name: celery-worker
    restart: always
    command: celery -A dsu worker -l info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=db_dsup
      - DB_USER=user_admin
      - DB_PASSWORD=pass_admin
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build: .
    container_name: celery-beat
    restart: always
    command: celery -A dsu beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - celery-worker
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=db_dsup
      - DB_USER=user_admin
      - DB_PASSWORD=pass_admin
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres-data:
    name: postgres-data

  redis-data:
    name: redis-data
