# Generated by Django 4.0.4 on 2025-02-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_secdelmembers_vote_in_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='dummyVoters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('voters', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('circle', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('f_link', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('district', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
