# Generated by Django 4.0.4 on 2025-02-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dummyvoters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyvoters',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
