# Generated by Django 4.0.4 on 2025-02-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_dummyvoters_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyvoters',
            name='made_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
