# Generated by Django 4.0.4 on 2025-02-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dummyvoters_made_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyvoters',
            name='circle',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dummyvoters',
            name='f_link',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dummyvoters',
            name='voters',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
