# Generated by Django 4.0.4 on 2025-03-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_voteoutsecdelmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteoutsecdelmember',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteIns', to='api.secdelmembers'),
        ),
    ]
