# Generated by Django 4.0.4 on 2025-03-08 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_voteoutsecdelmember_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteoutsecdelmember',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_outs', to='api.secdelmembers'),
        ),
    ]
