# Generated by Django 4.0.4 on 2025-04-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_putfarwardsecdelmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('item_list', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_for_candidate', models.BooleanField(default=False)),
                ('is_for_member', models.BooleanField(default=False)),
                ('is_for_delegate', models.BooleanField(default=False)),
                ('is_for_circle', models.BooleanField(default=False)),
                ('is_for_sec_del', models.BooleanField(default=False)),
                ('is_for_moda', models.BooleanField(default=False)),
                ('is_for_co_rep', models.BooleanField(default=False)),
                ('is_for_house_rep', models.BooleanField(default=False)),
            ],
        ),
    ]
