# Generated by Django 4.0.4 on 2025-04-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_statusitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusitems',
            name='sort',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The sort order of the message.', null=True),
        ),
        migrations.AlterField(
            model_name='statusitems',
            name='is_active',
            field=models.BooleanField(default=True, help_text='check this if the message is active status for circle...'),
        ),
        migrations.AlterField(
            model_name='statusitems',
            name='is_for_candidate',
            field=models.BooleanField(default=False, help_text='This message is for the candidate view.', verbose_name='Candidates?'),
        ),
        migrations.AlterField(
            model_name='statusitems',
            name='is_for_circle',
            field=models.BooleanField(default=False, help_text='Check this option if this message is associated with the circle.', verbose_name='Circle?'),
        ),
        migrations.AlterField(
            model_name='statusitems',
            name='is_for_co_rep',
            field=models.BooleanField(default=False, help_text='Check this option if this message is associated with the Member of Legislative Caucus.', verbose_name='Legislative Caucus?'),
        ),
        migrations.AlterField(
            model_name='statusitems',
            name='is_for_delegate',
            field=models.BooleanField(default=False, help_text='This message is for the delegate view.', verbose_name='Delegates?'),
        ),
        migrations.AlterField(
            model_name='statusitems',
            name='is_for_house_rep',
            field=models.BooleanField(default=False, help_text='Check this option if this message is associated with the Head of Legislative Caucus.', verbose_name='Head of Caucus?'),
        ),
        migrations.AlterField(
            model_name='statusitems',
            name='is_for_member',
            field=models.BooleanField(default=False, help_text='This message is for the member view.', verbose_name='Members?'),
        ),
        migrations.AlterField(
            model_name='statusitems',
            name='is_for_moda',
            field=models.BooleanField(default=False, help_text='Check this option if this message is associated with the Member of District Assembly.', verbose_name='District Assembly?'),
        ),
        migrations.AlterField(
            model_name='statusitems',
            name='is_for_sec_del',
            field=models.BooleanField(default=False, help_text='Check this option if this message is associated with the Second Delegate.', verbose_name='Second Delegate?'),
        ),
        migrations.AlterField(
            model_name='statusitems',
            name='item_list',
            field=models.TextField(blank=True, help_text='This field is for the list of items that the message is about.', null=True),
        ),
        migrations.AlterField(
            model_name='statusitems',
            name='message',
            field=models.TextField(help_text='The message to be displayed.'),
        ),
    ]
