# Generated by Django 4.0.4 on 2025-04-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_statusitems_sort_alter_statusitems_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusitems',
            name='is_candidate_waiting',
            field=models.BooleanField(default=False, help_text='check this if the message is for the candidate waiting status.'),
        ),
    ]
