# Generated by Django 4.0.4 on 2025-04-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_voteinsecdelmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='putfarwardsecdelmember',
            name='sec_del',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.secdelmodel'),
        ),
        migrations.AddField(
            model_name='voteinsecdelmember',
            name='sec_del',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.secdelmodel'),
        ),
        migrations.AddField(
            model_name='voteoutsecdelmember',
            name='sec_del',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.secdelmodel'),
        ),
    ]
