# Generated by Django 4.0.4 on 2025-04-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_putfarwardsecdelmember_sec_del_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secdelmembers',
            name='vote_in_count',
        ),
        migrations.RemoveField(
            model_name='secdelmembers',
            name='vote_out_count',
        ),
    ]
