# Generated by Django 4.0.4 on 2025-08-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_secdelmembers_vote_in_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secdelmodel',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
