# Generated by Django 4.0.4 on 2025-08-11 12:37

from django.db import migrations


def populate_secdel_contact_info(apps, schema_editor):
    """
    Create ContactInfo records for all existing SecDelMembers who are members
    but don't have a ContactInfo record yet.
    """
    SecDelMembers = apps.get_model('api', 'SecDelMembers')
    ContactInfo = apps.get_model('api', 'ContactInfo')
    
    # Get all SecDelMembers who are members but don't have ContactInfo
    members_without_contact = SecDelMembers.objects.filter(
        is_member=True
    ).exclude(
        contactinfo__isnull=False
    )
    
    contact_infos_to_create = []
    
    for member in members_without_contact:
        contact_info = ContactInfo(
            member=member,
            sec_del=member.sec_del,
            legal_name=member.user.users.legalName if hasattr(member.user, 'users') else None,
            address=member.user.users.address if hasattr(member.user, 'users') else None,
            email=member.user.email,
            contact_rules="Please contact during regular hours.",
            contact="Available via email.",
        )
        contact_infos_to_create.append(contact_info)
    
    # Bulk create for better performance
    if contact_infos_to_create:
        ContactInfo.objects.bulk_create(contact_infos_to_create)
        print(f"Created {len(contact_infos_to_create)} SecDel ContactInfo records")
    else:
        print("No SecDel ContactInfo records needed to be created")


def reverse_populate_secdel_contact_info(apps, schema_editor):
    """
    Remove ContactInfo records that were created by this migration
    """
    ContactInfo = apps.get_model('api', 'ContactInfo')
    
    # This is a simple reverse - in practice, you might want to be more selective
    # For now, we'll just print a message since we can't easily identify which records
    # were created by this migration vs. created normally
    print("Reverse migration: SecDel ContactInfo records remain (manual cleanup required)")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_contactinfo'),  # Updated to depend on ContactInfo model creation
    ]

    operations = [
        migrations.RunPython(populate_secdel_contact_info, reverse_populate_secdel_contact_info),
    ]
