# Generated by Django 4.0.4 on 2025-08-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_secdelmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contact_rules', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.secdelmembers')),
                ('sec_del', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.secdelmodel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
