# Generated by Django 4.0.4 on 2025-08-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_populate_secdel_contact_info'),
        ('api', '0024_populate_secdel_contact_info'),
    ]

    operations = [
    ]
