# Generated by Django 4.0.4 on 2026-09-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_backnforthchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='secdelmembers',
            name='succession_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
