# Generated by Django 4.0.4 on 2024-04-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'get_latest_by': ['number'], 'ordering': ('-created_at',)},
        ),
    ]
