# Generated by Django 4.0.4 on 2024-04-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_alter_bill_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='congress',
            field=models.IntegerField(null=True),
        ),
    ]
