# Generated by Django 4.0.4 on 2024-04-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bill_congress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='latest_action_date',
            field=models.DateField(null=True),
        ),
    ]
