# Generated by Django 4.0.4 on 2025-06-27 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0004_alter_bill_latest_action_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDelAdvisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisement', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_del_advisements', to='bills.bill')),
                ('fdel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdel_advisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('bill', 'fdel')},
            },
        ),
    ]
