# Generated by Django 4.0.4 on 2025-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_fdeladvisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdeladvisement',
            name='vote',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
