# Generated by Django 4.0.4 on 2025-07-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_fdeladvisement_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='url',
            new_name='congress_url',
        ),
    ]
