# Generated by Django 4.0.4 on 2023-11-21 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0024_remove_users_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0006_remove_bill_advice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.CharField(choices=[('Y', 'Yea'), ('N', 'Nay'), ('Pr', 'Present'), ('Px', 'Proxy')], default='Px', max_length=2)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill')),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.pod')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
