# Generated by Django 4.0.4 on 2025-07-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_rename_url_bill_congress_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='committee_meeting',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='committees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='introduced_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='sponsors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
