# Generated by Django 4.0.4 on 2025-07-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_bill_committee_meeting_bill_committees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
