# Generated by Django 4.0.4 on 2025-07-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_billusernotes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billusernotes',
            unique_together=set(),
        ),
    ]
