# Generated by Django 4.0.4 on 2025-07-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_billfirstdelnotes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billfirstdelnotes',
            unique_together=set(),
        ),
    ]
