# Generated by Django 4.0.4 on 2025-07-31 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0017_billhouserepnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAdvisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=2, null=True)),
                ('advisement', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_advisement', to='bills.bill')),
                ('fdel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdel_advisements', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_advisement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('bill', 'fdel')},
            },
        ),
        migrations.DeleteModel(
            name='FDelAdvisement',
        ),
    ]
