# Generated by Django 4.0.4 on 2025-07-31 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0018_billadvisement_delete_fdeladvisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billadvisement',
            name='fdel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fdel_advisements', to=settings.AUTH_USER_MODEL),
        ),
    ]
