# Generated by Django 4.0.4 on 2025-07-31 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0019_alter_billadvisement_fdel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billadvisement',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='billadvisement',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_advisements', to='bills.bill'),
        ),
        migrations.AlterField(
            model_name='billadvisement',
            name='type',
            field=models.CharField(choices=[('FD', 'First Delegate'), ('SD', 'Second Delegate'), ('MD', 'MoDa'), ('HL', 'HoLC'), ('HR', 'House Rep')], default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billadvisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_advisements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='billadvisement',
            unique_together={('bill', 'user', 'type')},
        ),
        migrations.RemoveField(
            model_name='billadvisement',
            name='fdel',
        ),
    ]
