# Generated by Django 4.0.4 on 2025-07-31 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0020_alter_billadvisement_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billvote',
            old_name='your_vote',
            new_name='vote',
        ),
        migrations.AlterField(
            model_name='billvote',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_votes', to='bills.bill'),
        ),
        migrations.AlterField(
            model_name='billvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='billvote',
            unique_together={('bill', 'voter', 'vote')},
        ),
        migrations.RemoveField(
            model_name='billvote',
            name='voted_by_fDel',
        ),
    ]
