# Generated by Django 4.0.4 on 2025-07-31 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0021_rename_your_vote_billvote_vote_alter_billvote_bill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billvote',
            old_name='vote',
            new_name='your_vote',
        ),
        migrations.AlterUniqueTogether(
            name='billvote',
            unique_together={('bill', 'voter')},
        ),
    ]
