# Generated by Django 4.0.4 on 2024-02-06 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0025_circlestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodMemberContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.podmember')),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.pod')),
            ],
        ),
    ]
