# Generated by Django 4.0.4 on 2024-03-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0026_podmembercontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='voterID',
        ),
        migrations.AddField(
            model_name='users',
            name='VVAT_Number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
