# Generated by Django 4.0.4 on 2024-04-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0030_alter_users_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vote.districts'),
        ),
    ]
