# Generated by Django 4.0.4 on 2024-04-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0031_alter_users_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleBackNForth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('circle', models.IntegerField()),
                ('sender', models.IntegerField()),
                ('message', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='CircleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('circle', models.IntegerField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_member', models.BooleanField(default=False)),
                ('is_delegate', models.BooleanField(default=False)),
                ('member_number', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_delegate', 'date_joined'],
            },
        ),
        migrations.CreateModel(
            name='CircleMember_put_farward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.IntegerField()),
                ('voter', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CircleMember_vote_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condidate', models.IntegerField()),
                ('voter', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CircleMember_vote_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condidate', models.IntegerField()),
                ('voter', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CircleMemberContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.IntegerField()),
                ('member', models.IntegerField()),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='Pod',
            new_name='Circle',
        ),
        migrations.RemoveField(
            model_name='podmember',
            name='pod',
        ),
        migrations.RemoveField(
            model_name='podmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='podmember_put_farward',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='podmember_put_farward',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='podmember_vote_in',
            name='condidate',
        ),
        migrations.RemoveField(
            model_name='podmember_vote_in',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='podmember_vote_out',
            name='condidate',
        ),
        migrations.RemoveField(
            model_name='podmember_vote_out',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='podmembercontact',
            name='member',
        ),
        migrations.RemoveField(
            model_name='podmembercontact',
            name='pod',
        ),
        migrations.DeleteModel(
            name='PodBackNForth',
        ),
        migrations.DeleteModel(
            name='PodMember',
        ),
        migrations.DeleteModel(
            name='PodMember_put_farward',
        ),
        migrations.DeleteModel(
            name='PodMember_vote_in',
        ),
        migrations.DeleteModel(
            name='PodMember_vote_out',
        ),
        migrations.DeleteModel(
            name='PodMemberContact',
        ),
    ]
