# Generated by Django 4.0.4 on 2024-04-12 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0032_circlebacknforth_circlemember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circlemember',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.circle'),
        ),
        migrations.AlterField(
            model_name='circlemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
