# Generated by Django 4.0.4 on 2024-04-12 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0033_alter_circlemember_circle_alter_circlemember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circlemember_vote_in',
            name='condidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteIns', to='vote.circlemember'),
        ),
        migrations.AlterField(
            model_name='circlemember_vote_in',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
