# Generated by Django 4.0.4 on 2024-04-12 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0035_alter_circlemember_put_farward_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circlebacknforth',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.circle'),
        ),
        migrations.AlterField(
            model_name='circlebacknforth',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='circlemembercontact',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.circle'),
        ),
        migrations.AlterField(
            model_name='circlemembercontact',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.circlemember'),
        ),
    ]
