# Generated by Django 4.0.4 on 2024-04-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0036_alter_circlebacknforth_circle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circlemember_vote_in',
            old_name='condidate',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='circlemember_vote_out',
            old_name='condidate',
            new_name='candidate',
        ),
    ]
