# Generated by Django 4.0.4 on 2024-04-25 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0038_circlemember_put_forward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleMember_put_farward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation_code', models.CharField(max_length=10)),
                ('FDel_election', models.BooleanField(default=False)),
                ('group_type', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.districts')),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_member', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('member_type', models.CharField(max_length=10)),
                ('is_delegate', models.BooleanField(default=False)),
                ('member_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_delegate', 'date_joined'],
            },
        ),
        migrations.CreateModel(
            name='GroupMemberContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.groupmember')),
            ],
        ),
        migrations.RemoveField(
            model_name='circle',
            name='district',
        ),
        migrations.RemoveField(
            model_name='circlemember',
            name='circle',
        ),
        migrations.RemoveField(
            model_name='circlemember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='circlemembercontact',
            name='circle',
        ),
        migrations.RemoveField(
            model_name='circlemembercontact',
            name='member',
        ),
        migrations.RemoveField(
            model_name='circlemember_vote_in',
            name='candidate',
        ),
        migrations.AddField(
            model_name='circlebacknforth',
            name='handle',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CircleMember_put_forward',
        ),
        migrations.DeleteModel(
            name='CircleMemberContact',
        ),
        migrations.AddField(
            model_name='circlemember_put_farward',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putFarward', to='vote.groupmember'),
        ),
        migrations.AddField(
            model_name='circlemember_put_farward',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circlemember_vote_in',
            name='recipient',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='voteIns', to='vote.groupmember'),
        ),
        migrations.AlterField(
            model_name='circlebacknforth',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.group'),
        ),
        migrations.AlterField(
            model_name='circlemember_vote_out',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteOuts', to='vote.groupmember'),
        ),
        migrations.DeleteModel(
            name='Circle',
        ),
        migrations.DeleteModel(
            name='CircleMember',
        ),
    ]
