# Generated by Django 4.0.4 on 2024-05-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0040_circlemember_put_forward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circlemember_put_forward',
            name='recipient',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='putForward', to='vote.groupmember'),
        ),
    ]
