# Generated by Django 4.0.4 on 2024-06-13 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0041_alter_circlemember_put_forward_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember_vote_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteIns', to='vote.groupmember')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='CircleMember_vote_out',
            new_name='GroupMember_vote_out',
        ),
        migrations.DeleteModel(
            name='CircleMember_vote_in',
        ),
    ]
