# Generated by Django 4.0.4 on 2025-03-28 20:57

from django.db import migrations, models

# this is the farward function that updates the current record of the model. 
def update_user_type(apps, schema_editor):
    Users = apps.get_model('vote', 'Users') 
    GroupMember = apps.get_model('vote', 'GroupMember') 
    SecDedMember = apps.get_model('api', 'SecDelMembers') 
    # upto this point the database has Circle (Group) and SecDel models. 
    # so we are going to change the userType for this two cases. 
    for user in Users.objects.all():
        if int(user.userType) == 0:
            user.userType = 'U0D0'
        elif int(user.userType) == 1:
            group = GroupMember.objects.filter(user=user.user).first() 
            if group and group.is_delegate:
                user.userType = 'U1D1'
            else:
                user.userType = 'U1D0'
        elif int(user.userType) == 2:
            secdel = SecDedMember.objects.filter(user=user.user).first() 
            if secdel and secdel.is_delegate:
                user.userType = 'U2D2'
            else:
                user.userType = 'U2D1'
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0047_alter_contactinfo_options_contactinfo_created_at_and_more'),
        ('api', '0004_rename_secdel_secdelmembers_sec_del'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userType',
            field=models.CharField(default='U0DO', max_length=4),
        ),
        migrations.RunPython(update_user_type),
    ]
