# Generated by Django 4.0.4 on 2025-03-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0048_alter_users_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userType',
            field=models.CharField(default='U0D0', max_length=4),
        ),
    ]
