# Generated by Django 4.0.4 on 2025-04-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0049_alter_users_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='circlemember_put_forward',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.group'),
        ),
        migrations.AddField(
            model_name='circlemember_vote_out',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.group'),
        ),
    ]
