# Generated by Django 4.0.4 on 2025-04-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0050_circlemember_put_forward_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
