# Generated by Django 4.0.4 on 2025-04-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0051_alter_districts_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='circlemember_vote_in',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.group'),
        ),
    ]
