# Generated by Django 4.0.4 on 2025-04-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0052_circlemember_vote_in_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verificationScore',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
