# Generated by Django 4.0.4 on 2025-08-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0053_alter_users_verificationscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
