# Generated by Django 4.0.4 on 2025-08-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0054_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verificationScore',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
