# Generated by Django 4.0.4 on 2025-08-10 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0055_alter_users_verificationscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateEligibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('target_group_type', models.CharField(max_length=20)),
                ('required_lower_group_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_eligible', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SuccessionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('removed', 'Removed from group'), ('promoted', 'Promoted to delegate'), ('demoted', 'Demoted from delegate'), ('cascade_removal', 'Cascade removal due to ineligibility')], max_length=20)),
                ('target_group_type', models.CharField(max_length=20)),
                ('target_group_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_username', models.CharField(max_length=150)),
                ('was_delegate', models.BooleanField(default=False)),
                ('promotion_method', models.CharField(blank=True, help_text='How delegate was chosen (votes, earliest_joined, etc)', max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SuccessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_group_type', models.CharField(help_text='Type of group where change originated', max_length=20)),
                ('trigger_group_id', models.PositiveIntegerField(help_text='ID of group where change originated')),
                ('old_delegate_username', models.CharField(help_text='Username of old delegate', max_length=150)),
                ('new_delegate_username', models.CharField(help_text='Username of new delegate', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='successionlog',
            index=models.Index(fields=['-created_at'], name='vote_succes_created_3ffdfd_idx'),
        ),
        migrations.AddIndex(
            model_name='successionlog',
            index=models.Index(fields=['trigger_group_type'], name='vote_succes_trigger_b97155_idx'),
        ),
        migrations.AddIndex(
            model_name='successionlog',
            index=models.Index(fields=['old_delegate_username'], name='vote_succes_old_del_d934cd_idx'),
        ),
        migrations.AddField(
            model_name='successionaction',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='vote.successionlog'),
        ),
        migrations.AddField(
            model_name='delegateeligibilitycheck',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='vote.successionlog'),
        ),
    ]
