# Generated by Django 4.0.4 on 2025-08-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0056_add_succession_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successionaction',
            name='action',
            field=models.CharField(choices=[('removed', 'Removed from group'), ('promoted', 'Promoted to delegate'), ('demoted', 'Demoted from delegate'), ('cascade_removal', 'Cascade removal due to ineligibility'), ('user_type_update', 'Updated user type after removal')], max_length=25),
        ),
    ]
