# Generated by Django 4.0.4 on 2025-08-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0057_update_succession_action_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.group'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
