# Generated by Django 4.0.4 on 2026-09-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0059_populate_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='eligibility_attestation_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='eligibility_attested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='eligibility_attested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
