# Generated by Django 4.0.4 on 2026-09-06 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0060_users_eligibility_attestation_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('public_key', models.TextField()),
                ('algorithm', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encryption_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CircleKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('public_key', models.TextField()),
                ('algorithm', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encryption_keys', to='vote.group')),
            ],
        ),
        migrations.CreateModel(
            name='CircleKeyEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapped_key', models.TextField()),
                ('algorithm', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circle_key_envelopes', to='vote.accountkey')),
                ('circle_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_envelopes', to='vote.circlekey')),
                ('group_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_envelopes', to='vote.groupmember')),
            ],
        ),
        migrations.CreateModel(
            name='CircleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('ciphertext', models.TextField()),
                ('algorithm', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='vote.groupmember')),
            ],
        ),
        migrations.AddConstraint(
            model_name='circlekeyenvelope',
            constraint=models.UniqueConstraint(fields=('circle_key', 'group_member'), name='unique_circle_key_member_envelope'),
        ),
        migrations.AddConstraint(
            model_name='circlekey',
            constraint=models.UniqueConstraint(fields=('group', 'version'), name='unique_circle_key_version'),
        ),
        migrations.AddConstraint(
            model_name='accountkey',
            constraint=models.UniqueConstraint(fields=('user', 'version'), name='unique_account_key_version'),
        ),
    ]
