# Generated by Django 4.0.4 on 2026-09-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0061_accountkey_circlekey_circlekeyenvelope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='succession_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
