# Generated by Django 4.0.4 on 2025-04-19 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import moda.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0052_circlemember_vote_in_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(default=moda.models.generate_unique_code, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation_key', models.PositiveBigIntegerField(default=moda.models.generate_unique_invitation_key, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vote.districts')),
            ],
        ),
        migrations.CreateModel(
            name='ModaMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delegate', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moda.modamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_delegate', 'joined_at'],
            },
        ),
    ]
