# Generated by Django 4.0.4 on 2025-04-19 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moda', '0002_voteoutmodamember_voteinmodamember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putfarwardmodamember',
            name='moda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moda.modamodel'),
        ),
        migrations.AlterField(
            model_name='voteinmodamember',
            name='moda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moda.modamodel'),
        ),
        migrations.AlterField(
            model_name='voteoutmodamember',
            name='moda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moda.modamodel'),
        ),
    ]
