# Generated by Django 4.0.4 on 2025-08-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moda', '0003_alter_putfarwardmodamember_moda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modamodel',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
