# Generated by Django 4.0.4 on 2025-08-11 14:04

from django.db import migrations


def populate_moda_member_contact_info(apps, schema_editor):
    ModaMembers = apps.get_model('moda', 'ModaMembers')
    ModaMemberContact = apps.get_model('moda', 'ModaMemberContact')
    
    # Get all Moda members and create contact info for them
    moda_members = ModaMembers.objects.all()
    contact_records = []
    
    for member in moda_members:
        contact_records.append(
            ModaMemberContact(
                member=member,
                moda=member.moda,  # Add the moda reference
                legal_name='',
                contact_rules='',
                address='',
                contact='',
                phone='',
                email=''
            )
        )
    
    # Bulk create all contact info records
    ModaMemberContact.objects.bulk_create(contact_records, ignore_conflicts=True)


def reverse_populate_moda_member_contact_info(apps, schema_editor):
    ModaMemberContact = apps.get_model('moda', 'ModaMemberContact')
    ModaMemberContact.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('moda', '0005_modamembercontact'),
    ]

    operations = [
        migrations.RunPython(
            populate_moda_member_contact_info,
            reverse_populate_moda_member_contact_info
        ),
    ]
