# Generated by Django 4.0.4 on 2025-08-15 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moda', '0006_populate_moda_member_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModaBackNForthChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('moda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='moda.modamodel')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='moda.modabacknforthchat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='modabacknforthchat',
            index=models.Index(fields=['moda', '-timestamp'], name='moda_modaba_moda_id_77b7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='modabacknforthchat',
            index=models.Index(fields=['sender'], name='moda_modaba_sender__4f1521_idx'),
        ),
        migrations.AddIndex(
            model_name='modabacknforthchat',
            index=models.Index(fields=['is_deleted'], name='moda_modaba_is_dele_2d2df2_idx'),
        ),
    ]
