# Generated by Django 4.0.4 on 2026-09-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moda', '0007_modabacknforthchat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modamembers',
            name='succession_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
