# Generated by Django 4.0.4 on 2025-07-30 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rep.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0053_alter_users_verificationscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(default=rep.models.generate_unique_code, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation_key', models.PositiveBigIntegerField(default=rep.models.generate_unique_invitation_key, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vote.districts')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictCouncilMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delegate', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district_council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rep.districtcouncil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_delegate', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='VoteOutDistrictCouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_outs', to='rep.districtcouncilmembers')),
                ('district_council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rep.districtcouncil')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteInDistrictCouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_ins', to='rep.districtcouncilmembers')),
                ('district_council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rep.districtcouncil')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PutForwardDistrictCouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='put_forward', to='rep.districtcouncilmembers')),
                ('district_council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rep.districtcouncil')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
