# Generated by Django 4.0.4 on 2025-08-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtcouncil',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
