# Generated by Django 4.0.4 on 2025-08-11 13:54

from django.db import migrations


def populate_district_council_member_contact_info(apps, schema_editor):
    DistrictCouncilMembers = apps.get_model('rep', 'DistrictCouncilMembers')
    DistrictCouncilMemberContact = apps.get_model('rep', 'DistrictCouncilMemberContact')
    
    # Get all DistrictCouncil members and create contact info for them
    dc_members = DistrictCouncilMembers.objects.all()
    contact_records = []
    
    for member in dc_members:
        contact_records.append(
            DistrictCouncilMemberContact(
                member=member,
                first_name='',
                last_name='',
                middle_name='',
                phone='',
                email='',
                address=''
            )
        )
    
    # Bulk create all contact info records
    DistrictCouncilMemberContact.objects.bulk_create(contact_records, ignore_conflicts=True)


def reverse_populate_district_council_member_contact_info(apps, schema_editor):
    DistrictCouncilMemberContact = apps.get_model('rep', 'DistrictCouncilMemberContact')
    DistrictCouncilMemberContact.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rep', '0004_districtcouncilmembercontact'),
    ]

    operations = [
        migrations.RunPython(
            populate_district_council_member_contact_info,
            reverse_populate_district_council_member_contact_info
        ),
    ]
