# Generated by Django 4.0.4 on 2025-08-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rep', '0003_populate_district_council_member_contact_info'),
        ('rep', '0005_populate_district_council_member_contact_info'),
    ]

    operations = [
    ]
