# Generated by Django 4.0.4 on 2025-08-16 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rep', '0005_populate_district_council_member_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCouncilBackNForth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('district_council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='rep.districtcouncil')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='rep.districtcouncilbacknforth')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='districtcouncilbacknforth',
            index=models.Index(fields=['district_council', '-timestamp'], name='rep_distric_distric_13faaf_idx'),
        ),
        migrations.AddIndex(
            model_name='districtcouncilbacknforth',
            index=models.Index(fields=['sender'], name='rep_distric_sender__9adae3_idx'),
        ),
        migrations.AddIndex(
            model_name='districtcouncilbacknforth',
            index=models.Index(fields=['is_deleted'], name='rep_distric_is_dele_ae258b_idx'),
        ),
    ]
